### ISSUE TITLE
Adding to the beginning

### ISSUE THREAD

**Issue by hacker1024** [kranfix/dart-circularbuffer#13]
Would it be possible to add a function to add an item to the beginning of the buffer, as if it pushes everything the other way?

**Comment by kranfix** [comment]
Technically, it's possible. But let's remember that the `CircularBuffer` has a fixed capacity.  
  
Could you propose an API for this?

**Comment by Erhannis** [comment]
Conceptually it seems pretty straightforward - just move the "start index" earlier by one, wrapping around if necessary.  Now, under the hood, I imagine there might be moderate work involved making sure everything handles the index and size calculations; probably not terrible.  I'd probably go with `addFirst(x)` or `addHead(x)` for the api, something like that.  I'd make a fork myself, and may yet, but the code looks interconnected enough that I'd want to understand all of it first to make sure I'm not breaking something.

**Comment by kranfix** [comment]
I see, I think I can add the `addHead` method for a fixed buffer capacity.
Let me try something on the weekend before creating a fork, please.

**Comment by kranfix** [comment]
Ready! I added the `addHead` method.
